# Generated by Django 4.0.3 on 2022-03-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Street',
            new_name='street',
        ),
    ]
